# Generated by Django 3.2.3 on 2021-06-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoApp.department')),
            ],
        ),
    ]
