# Generated by Django 3.2 on 2021-06-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_auto_20210606_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DemoApp.department')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoApp.faculty')),
            ],
        ),
    ]
